.TH "ull.AllFilters" 3 "Thu Dec 1 2022" "Version 1.0" "ProyectoFinalLDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ull.AllFilters
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBull\&.Filter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAllFilters\fP ()"
.br
.ti -1c
.RI "void \fBaddFilter\fP (\fBFilter\fP f)"
.br
.ti -1c
.RI "boolean \fBsatisfies\fP (String id)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ull\&.AllFilters\&.AllFilters ()"

.SH "Member Function Documentation"
.PP 
.SS "void ull\&.AllFilters\&.addFilter (\fBFilter\fP f)"

.SS "boolean ull\&.AllFilters\&.satisfies (String id)"

.PP
Implements \fBull\&.Filter\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ProyectoFinalLDH from the source code\&.
