.TH "ull.Filter" 3 "Thu Dec 1 2022" "Version 1.0" "ProyectoFinalLDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ull.Filter
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBull\&.AllFilters\fP, \fBull\&.DirectorsFilter\fP, \fBull\&.GenreFilter\fP, \fBull\&.MinutesFilter\fP, \fBull\&.TrueFilter\fP, and \fBull\&.YearAfterFilter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "boolean \fBsatisfies\fP (String id)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "boolean ull\&.Filter\&.satisfies (String id)"

.PP
Implemented in \fBull\&.AllFilters\fP, \fBull\&.DirectorsFilter\fP, \fBull\&.GenreFilter\fP, \fBull\&.MinutesFilter\fP, \fBull\&.TrueFilter\fP, and \fBull\&.YearAfterFilter\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ProyectoFinalLDH from the source code\&.
