.TH "es.ull.etsii.Filters.Filter" 3 "Lunes, 9 de Enero de 2023" "Version 1.0" "ProyectoFinalLDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
es.ull.etsii.Filters.Filter
.SH SYNOPSIS
.br
.PP
.PP
Heredado por \fBes\&.ull\&.etsii\&.Filters\&.AllFilters\fP, \fBes\&.ull\&.etsii\&.Filters\&.CountryFilter\fP, \fBes\&.ull\&.etsii\&.Filters\&.DirectorsFilter\fP, \fBes\&.ull\&.etsii\&.Filters\&.GenreFilter\fP, \fBes\&.ull\&.etsii\&.Filters\&.MinutesFilter\fP, \fBes\&.ull\&.etsii\&.Filters\&.TrueFilter\fP y \fBes\&.ull\&.etsii\&.Filters\&.YearFilter\fP\&.
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "boolean \fBsatisfies\fP (String id)"
.br
.in -1c
.SH "Descripción detallada"
.PP 
Interfaz filtro 
.SH "Documentación de las funciones miembro"
.PP 
.SS "boolean es\&.ull\&.etsii\&.Filters\&.Filter\&.satisfies (String id)"
Interfaz filtro 
.PP
\fBParámetros\fP
.RS 4
\fIid\fP Identificador de una película 
.RE
.PP

.PP
Implementado en \fBes\&.ull\&.etsii\&.Filters\&.AllFilters\fP, \fBes\&.ull\&.etsii\&.Filters\&.CountryFilter\fP, \fBes\&.ull\&.etsii\&.Filters\&.DirectorsFilter\fP, \fBes\&.ull\&.etsii\&.Filters\&.GenreFilter\fP, \fBes\&.ull\&.etsii\&.Filters\&.MinutesFilter\fP, \fBes\&.ull\&.etsii\&.Filters\&.TrueFilter\fP y \fBes\&.ull\&.etsii\&.Filters\&.YearFilter\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para ProyectoFinalLDH del código fuente\&.
