.TH "es.ull.etsii.Recommendations.RecommendationRunner" 3 "Lunes, 9 de Enero de 2023" "Version 1.0" "ProyectoFinalLDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
es.ull.etsii.Recommendations.RecommendationRunner
.SH SYNOPSIS
.br
.PP
.PP
Herencias \fBes\&.ull\&.etsii\&.Recommendations\&.Recommender\fP\&.
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "ArrayList< String > \fBgetItemsToRate\fP ()"
.br
.ti -1c
.RI "void \fBprintRecommendationsFor\fP (String webRaterID)"
.br
.in -1c
.SH "Descripción detallada"
.PP 

.PP
\fBAutor\fP
.RS 4
Stanislav Rakitov 
.RE
.PP

.SH "Documentación de las funciones miembro"
.PP 
.SS "ArrayList< String > es\&.ull\&.etsii\&.Recommendations\&.RecommendationRunner\&.getItemsToRate ()"
Este método devuelve una lista de ID de películas que se usarán para buscar las películas en el MovieDatabase y preséntelos a los usuarios para que los califiquen\&.
.PP
Las películas devueltas en la lista se mostrarán en una página web, por lo que el número que elija puede afectar el tiempo de carga de la página y la disposición de los usuarios a calificar las películas\&. Para ejemplo, 10-20 debería estar bien, 50 o más sería demasiado\&.
.PP
No hay restricciones sobre el método que utiliza para generar esta lista de películas: la mayoría películas recientes, películas de un género específico, películas elegidas al azar o simplemente tu favorita películas\&.
.PP
Las clasificaciones de estas películas crearán el perfil de un nuevo evaluador que se usará para comparar con para encontrar recomendaciones\&. 
.PP
Implementa \fBes\&.ull\&.etsii\&.Recommendations\&.Recommender\fP\&.
.SS "void es\&.ull\&.etsii\&.Recommendations\&.RecommendationRunner\&.printRecommendationsFor (String webRaterID)"
Este método no devuelve nada, pero imprime una tabla HTML de las películas recomendadas para el evaluador dado\&.
.PP
El HTML impreso se mostrará en una página web, por lo que el número que elija mostrar puede afecta el tiempo que tarda la página en cargarse\&. Por ejemplo, es posible que desee limitar el número impreso solo a las 20-50 mejores películas recomendadas o a las películas no calificadas por el calificador dado\&.
.PP
También puede incluir estilo CSS para su tabla utilizando el <estilo> etiqueta antes de imprimir la mesa\&. No hay restricciones sobre qué películas imprime, en qué orden las imprime, o qué información incluyes sobre cada película\&.
.PP
\fBParámetros\fP
.RS 4
\fIwebRaterID\fP el ID de un nuevo evaluador que ya se ha agregado a RaterDatabase con calificaciones de las películas devueltas por el método getItemsToRate 
.RE
.PP

.PP
Implementa \fBes\&.ull\&.etsii\&.Recommendations\&.Recommender\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para ProyectoFinalLDH del código fuente\&.
