.TH "es.ull.etsii.Rate.EfficientRater" 3 "Sat Dec 3 2022" "Version 1.0" "ProyectoFinalLDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
es.ull.etsii.Rate.EfficientRater
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBes\&.ull\&.etsii\&.Rater\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEfficientRater\fP (String id)"
.br
.ti -1c
.RI "void \fBaddRating\fP (String movieID, double rating)"
.br
.ti -1c
.RI "boolean \fBhasRating\fP (String movieID)"
.br
.ti -1c
.RI "String \fBgetID\fP ()"
.br
.ti -1c
.RI "double \fBgetRating\fP (String movieID)"
.br
.ti -1c
.RI "int \fBnumRatings\fP ()"
.br
.ti -1c
.RI "ArrayList< String > \fBgetItemsRated\fP ()"
.br
.ti -1c
.RI "HashMap< String, \fBRating\fP > \fBgetMyRatings\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
The class \fBEfficientRater\fP keeps track of one rater and all their ratings\&.
.PP
\fBAuthor\fP
.RS 4
Stanislav Rakitov 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "es\&.ull\&.etsii\&.EfficientRater\&.EfficientRater (String id)"

.SH "Member Function Documentation"
.PP 
.SS "void es\&.ull\&.etsii\&.EfficientRater\&.addRating (String movieID, double rating)"

.PP
Implements \fBes\&.ull\&.etsii\&.Rater\fP\&.
.SS "String es\&.ull\&.etsii\&.EfficientRater\&.getID ()"

.PP
Implements \fBes\&.ull\&.etsii\&.Rater\fP\&.
.SS "ArrayList< String > es\&.ull\&.etsii\&.EfficientRater\&.getItemsRated ()"

.PP
Implements \fBes\&.ull\&.etsii\&.Rater\fP\&.
.SS "HashMap< String, \fBRating\fP > es\&.ull\&.etsii\&.EfficientRater\&.getMyRatings ()"

.PP
Implements \fBes\&.ull\&.etsii\&.Rater\fP\&.
.SS "double es\&.ull\&.etsii\&.EfficientRater\&.getRating (String movieID)"

.PP
Implements \fBes\&.ull\&.etsii\&.Rater\fP\&.
.SS "boolean es\&.ull\&.etsii\&.EfficientRater\&.hasRating (String movieID)"

.PP
Implements \fBes\&.ull\&.etsii\&.Rater\fP\&.
.SS "int es\&.ull\&.etsii\&.EfficientRater\&.numRatings ()"

.PP
Implements \fBes\&.ull\&.etsii\&.Rater\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ProyectoFinalLDH from the source code\&.
