.TH "es.ull.etsii" 3 "Miércoles, 4 de Enero de 2023" "Version 1.0" "ProyectoFinalLDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
es.ull.etsii
.SH SYNOPSIS
.br
.PP
.SS "Paquetes"

.in +1c
.ti -1c
.RI "package \fBFilters\fP"
.br
.ti -1c
.RI "package \fBMovies\fP"
.br
.ti -1c
.RI "package \fBRate\fP"
.br
.ti -1c
.RI "package \fBRatings\fP"
.br
.ti -1c
.RI "package \fBRecommendations\fP"
.br
.in -1c
.SS "Clases"

.in +1c
.ti -1c
.RI "class \fBMain\fP"
.br
.in -1c
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para ProyectoFinalLDH del código fuente\&.
