.TH "es.ull.etsii.Ratings.PersonalRatingOption" 3 "Lunes, 9 de Enero de 2023" "Version 1.0" "ProyectoFinalLDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
es.ull.etsii.Ratings.PersonalRatingOption
.SH SYNOPSIS
.br
.PP
.SS "Métodos públicos estáticos"

.in +1c
.ti -1c
.RI "static void \fBmenu\fP ()"
.br
.in -1c
.SH "Documentación de las funciones miembro"
.PP 
.SS "static void es\&.ull\&.etsii\&.Ratings\&.PersonalRatingOption\&.menu ()\fC [static]\fP"


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para ProyectoFinalLDH del código fuente\&.
