.TH "C:/Users/roberto/IdeaProjects/LDH_PFInal/src/main/java/es/ull/etsii/Filters/MinutesFilter.java" 3 "Miércoles, 4 de Enero de 2023" "Version 1.0" "ProyectoFinalLDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/roberto/IdeaProjects/LDH_PFInal/src/main/java/es/ull/etsii/Filters/MinutesFilter.java
.SH SYNOPSIS
.br
.PP
.SS "Clases"

.in +1c
.ti -1c
.RI "class \fBes\&.ull\&.etsii\&.Filters\&.MinutesFilter\fP"
.br
.in -1c
.SS "Paquetes"

.in +1c
.ti -1c
.RI "package \fBes\&.ull\&.etsii\&.Filters\fP"
.br
.in -1c
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para ProyectoFinalLDH del código fuente\&.
