.TH "C:/Users/roberto/IdeaProjects/LDH_PFInal/src/main/java/es/courserajava/edu/duke Directory Reference" 3 "Thu Dec 29 2022" "Version 1.0" "ProyectoFinalLDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/roberto/IdeaProjects/LDH_PFInal/src/main/java/es/courserajava/edu/duke Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBFileResource\&.java\fP"
.br
.ti -1c
.RI "file \fBFileSelector\&.java\fP"
.br
.ti -1c
.RI "file \fBImageFrame\&.java\fP"
.br
.ti -1c
.RI "file \fBImageResource\&.java\fP"
.br
.ti -1c
.RI "file \fBpackage\-info\&.java\fP"
.br
.ti -1c
.RI "file \fBPixel\&.java\fP"
.br
.ti -1c
.RI "file \fBPoint\&.java\fP"
.br
.ti -1c
.RI "file \fBRangeResource\&.java\fP"
.br
.ti -1c
.RI "file \fBResourceException\&.java\fP"
.br
.ti -1c
.RI "file \fBShape\&.java\fP"
.br
.ti -1c
.RI "file \fBStorageResource\&.java\fP"
.br
.ti -1c
.RI "file \fBTextIterable\&.java\fP"
.br
.ti -1c
.RI "file \fBURLResource\&.java\fP"
.br
.in -1c
