.TH "C:/Users/roberto/IdeaProjects/LDH_PFInal/src/main/java/es/ull/etsii Directory Reference" 3 "Sat Dec 3 2022" "Version 1.0" "ProyectoFinalLDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/roberto/IdeaProjects/LDH_PFInal/src/main/java/es/ull/etsii Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAllFilters\&.java\fP"
.br
.ti -1c
.RI "file \fBDirectorsFilter\&.java\fP"
.br
.ti -1c
.RI "file \fBEfficientRater\&.java\fP"
.br
.ti -1c
.RI "file \fBFilter\&.java\fP"
.br
.ti -1c
.RI "file \fBFirstRatings\&.java\fP"
.br
.ti -1c
.RI "file \fBFourthRatings\&.java\fP"
.br
.ti -1c
.RI "file \fBGenreFilter\&.java\fP"
.br
.ti -1c
.RI "file \fBMain\&.java\fP"
.br
.ti -1c
.RI "file \fBMinutesFilter\&.java\fP"
.br
.ti -1c
.RI "file \fBMovie\&.java\fP"
.br
.ti -1c
.RI "file \fBMovieDatabase\&.java\fP"
.br
.ti -1c
.RI "file \fBMovieRunnerSimilarRatings\&.java\fP"
.br
.ti -1c
.RI "file \fBRater\&.java\fP"
.br
.ti -1c
.RI "file \fBRaterDatabase\&.java\fP"
.br
.ti -1c
.RI "file \fBRating\&.java\fP"
.br
.ti -1c
.RI "file \fBRecommendationRunner\&.java\fP"
.br
.ti -1c
.RI "file \fBRecommender\&.java\fP"
.br
.ti -1c
.RI "file \fBTrueFilter\&.java\fP"
.br
.ti -1c
.RI "file \fBYearAfterFilter\&.java\fP"
.br
.in -1c
