.TH "C:/Users/roberto/IdeaProjects/LDH_PFInal/src/main/java/es/ull/etsii Directory Reference" 3 "Thu Dec 29 2022" "Version 1.0" "ProyectoFinalLDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/roberto/IdeaProjects/LDH_PFInal/src/main/java/es/ull/etsii Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBFilters\fP"
.br
.ti -1c
.RI "directory \fBMainProgram\fP"
.br
.ti -1c
.RI "directory \fBMovies\fP"
.br
.ti -1c
.RI "directory \fBRate\fP"
.br
.ti -1c
.RI "directory \fBRatings\fP"
.br
.ti -1c
.RI "directory \fBRecommendations\fP"
.br
.in -1c
