.TH "es.apachecsv.org.apache.commons.csv.CSVFormat.Predefined" 3 "Thu Dec 29 2022" "Version 1.0" "ProyectoFinalLDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
es.apachecsv.org.apache.commons.csv.CSVFormat.Predefined
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPredefined\fP (final \fBCSVFormat\fP format)"
.br
.ti -1c
.RI "\fBCSVFormat\fP \fBgetFormat\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBDefault\fP =(\fBCSVFormat\&.DEFAULT\fP)"
.br
.ti -1c
.RI "\fBExcel\fP =(\fBCSVFormat\&.EXCEL\fP)"
.br
.ti -1c
.RI "\fBInformixUnload\fP =(\fBCSVFormat\&.INFORMIX_UNLOAD\fP)"
.br
.ti -1c
.RI "\fBInformixUnloadCsv\fP =(\fBCSVFormat\&.INFORMIX_UNLOAD_CSV\fP)"
.br
.ti -1c
.RI "\fBMySQL\fP =(\fBCSVFormat\&.MYSQL\fP)"
.br
.ti -1c
.RI "\fBRFC4180\fP =(CSVFormat\&.RFC4180)"
.br
.ti -1c
.RI "\fBTDF\fP =(CSVFormat\&.TDF)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Predefines formats\&.
.PP
\fBSince\fP
.RS 4
1\&.2 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "es\&.apachecsv\&.org\&.apache\&.commons\&.csv\&.CSVFormat\&.Predefined\&.Predefined (final \fBCSVFormat\fP format)"

.SH "Member Function Documentation"
.PP 
.SS "\fBCSVFormat\fP es\&.apachecsv\&.org\&.apache\&.commons\&.csv\&.CSVFormat\&.Predefined\&.getFormat ()"
Gets the format\&.
.PP
\fBReturns\fP
.RS 4
the format\&. 
.RE
.PP

.SH "Member Data Documentation"
.PP 
.SS "es\&.apachecsv\&.org\&.apache\&.commons\&.csv\&.CSVFormat\&.Predefined\&.Default =(\fBCSVFormat\&.DEFAULT\fP)"

.PP
\fBSee also\fP
.RS 4
\fBCSVFormat::DEFAULT\fP 
.RE
.PP

.SS "es\&.apachecsv\&.org\&.apache\&.commons\&.csv\&.CSVFormat\&.Predefined\&.Excel =(\fBCSVFormat\&.EXCEL\fP)"

.PP
\fBSee also\fP
.RS 4
\fBCSVFormat::EXCEL\fP 
.RE
.PP

.SS "es\&.apachecsv\&.org\&.apache\&.commons\&.csv\&.CSVFormat\&.Predefined\&.InformixUnload =(\fBCSVFormat\&.INFORMIX_UNLOAD\fP)"

.PP
\fBSee also\fP
.RS 4
\fBCSVFormat::INFORMIX_UNLOAD\fP 
.RE
.PP
\fBSince\fP
.RS 4
1\&.3 
.RE
.PP

.SS "es\&.apachecsv\&.org\&.apache\&.commons\&.csv\&.CSVFormat\&.Predefined\&.InformixUnloadCsv =(\fBCSVFormat\&.INFORMIX_UNLOAD_CSV\fP)"

.PP
\fBSee also\fP
.RS 4
\fBCSVFormat::INFORMIX_UNLOAD_CSV\fP 
.RE
.PP
\fBSince\fP
.RS 4
1\&.3 
.RE
.PP

.SS "es\&.apachecsv\&.org\&.apache\&.commons\&.csv\&.CSVFormat\&.Predefined\&.MySQL =(\fBCSVFormat\&.MYSQL\fP)"

.PP
\fBSee also\fP
.RS 4
\fBCSVFormat::MYSQL\fP 
.RE
.PP

.SS "es\&.apachecsv\&.org\&.apache\&.commons\&.csv\&.CSVFormat\&.Predefined\&.RFC4180 =(CSVFormat\&.RFC4180)"

.PP
\fBSee also\fP
.RS 4
\fBCSVFormat::RFC4180\fP 
.RE
.PP

.SS "es\&.apachecsv\&.org\&.apache\&.commons\&.csv\&.CSVFormat\&.Predefined\&.TDF =(CSVFormat\&.TDF)"

.PP
\fBSee also\fP
.RS 4
\fBCSVFormat::TDF\fP 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for ProyectoFinalLDH from the source code\&.
