.TH "es.apachecsv.org.apache.commons.csv.CSVPrinter" 3 "Thu Dec 29 2022" "Version 1.0" "ProyectoFinalLDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
es.apachecsv.org.apache.commons.csv.CSVPrinter
.SH SYNOPSIS
.br
.PP
.PP
Inherits Flushable, and Closeable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCSVPrinter\fP (final Appendable out, final \fBCSVFormat\fP format)  throws IOException "
.br
.ti -1c
.RI "void \fBclose\fP ()  throws IOException "
.br
.ti -1c
.RI "void \fBflush\fP ()  throws IOException "
.br
.ti -1c
.RI "Appendable \fBgetOut\fP ()"
.br
.ti -1c
.RI "void \fBprint\fP (final Object value)  throws IOException "
.br
.ti -1c
.RI "void \fBprintComment\fP (final String comment)  throws IOException "
.br
.ti -1c
.RI "void \fBprintln\fP ()  throws IOException "
.br
.ti -1c
.RI "void \fBprintRecord\fP (final Iterable<?> values)  throws IOException "
.br
.ti -1c
.RI "void \fBprintRecord\fP (final Object\&.\&.\&. values)  throws IOException "
.br
.ti -1c
.RI "void \fBprintRecords\fP (final Iterable<?> values)  throws IOException "
.br
.ti -1c
.RI "void \fBprintRecords\fP (final Object\&.\&.\&. values)  throws IOException "
.br
.ti -1c
.RI "void \fBprintRecords\fP (final ResultSet resultSet)  throws SQLException, IOException "
.br
.in -1c
.SH "Detailed Description"
.PP 
Prints values in a CSV format\&.
.PP
\fBVersion\fP
.RS 4
.RE
.PP
\fBId\fP
.RS 4
\fBCSVPrinter\&.java\fP 1743430 2016-05-11 21:09:48Z ggregory 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "es\&.apachecsv\&.org\&.apache\&.commons\&.csv\&.CSVPrinter\&.CSVPrinter (final Appendable out, final \fBCSVFormat\fP format) throws IOException"
Creates a printer that will print values to the given stream following the \fBCSVFormat\fP\&. 
.PP
Currently, only a pure encapsulation format or a pure escaping format is supported\&. Hybrid formats (encapsulation and escaping with a different character) are not supported\&. 
.PP
\fBParameters\fP
.RS 4
\fIout\fP stream to which to print\&. Must not be null\&. 
.br
\fIformat\fP the CSV format\&. Must not be null\&. 
.RE
.PP
\fBExceptions\fP
.RS 4
\fIIOException\fP thrown if the optional header cannot be printed\&. 
.br
\fIIllegalArgumentException\fP thrown if the parameters of the format are inconsistent or if either out or format are null\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void es\&.apachecsv\&.org\&.apache\&.commons\&.csv\&.CSVPrinter\&.close () throws IOException"

.SS "void es\&.apachecsv\&.org\&.apache\&.commons\&.csv\&.CSVPrinter\&.flush () throws IOException"
Flushes the underlying stream\&.
.PP
\fBExceptions\fP
.RS 4
\fIIOException\fP If an I/O error occurs 
.RE
.PP

.SS "Appendable es\&.apachecsv\&.org\&.apache\&.commons\&.csv\&.CSVPrinter\&.getOut ()"
Gets the target Appendable\&.
.PP
\fBReturns\fP
.RS 4
the target Appendable\&. 
.RE
.PP

.SS "void es\&.apachecsv\&.org\&.apache\&.commons\&.csv\&.CSVPrinter\&.print (final Object value) throws IOException"
Prints the string as the next value on the line\&. The value will be escaped or encapsulated as needed\&.
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP value to be output\&. 
.RE
.PP
\fBExceptions\fP
.RS 4
\fIIOException\fP If an I/O error occurs 
.RE
.PP

.SS "void es\&.apachecsv\&.org\&.apache\&.commons\&.csv\&.CSVPrinter\&.printComment (final String comment) throws IOException"
Prints a comment on a new line among the delimiter separated values\&.
.PP
Comments will always begin on a new line and occupy a least one full line\&. The character specified to start comments and a space will be inserted at the beginning of each new line in the comment\&. 
.PP
If comments are disabled in the current CSV format this method does nothing\&.
.PP
\fBParameters\fP
.RS 4
\fIcomment\fP the comment to output 
.RE
.PP
\fBExceptions\fP
.RS 4
\fIIOException\fP If an I/O error occurs 
.RE
.PP

.SS "void es\&.apachecsv\&.org\&.apache\&.commons\&.csv\&.CSVPrinter\&.println () throws IOException"
Outputs the record separator\&.
.PP
\fBExceptions\fP
.RS 4
\fIIOException\fP If an I/O error occurs 
.RE
.PP

.SS "void es\&.apachecsv\&.org\&.apache\&.commons\&.csv\&.CSVPrinter\&.printRecord (final Iterable<?> values) throws IOException"
Prints the given values a single record of delimiter separated values followed by the record separator\&.
.PP
The values will be quoted if needed\&. Quotes and newLine characters will be escaped\&. This method adds the record separator to the output after printing the record, so there is no need to call \fC\fBprintln()\fP\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalues\fP values to output\&. 
.RE
.PP
\fBExceptions\fP
.RS 4
\fIIOException\fP If an I/O error occurs 
.RE
.PP

.SS "void es\&.apachecsv\&.org\&.apache\&.commons\&.csv\&.CSVPrinter\&.printRecord (final Object\&.\&.\&. values) throws IOException"
Prints the given values a single record of delimiter separated values followed by the record separator\&.
.PP
The values will be quoted if needed\&. Quotes and newLine characters will be escaped\&. This method adds the record separator to the output after printing the record, so there is no need to call \fC\fBprintln()\fP\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalues\fP values to output\&. 
.RE
.PP
\fBExceptions\fP
.RS 4
\fIIOException\fP If an I/O error occurs 
.RE
.PP

.SS "void es\&.apachecsv\&.org\&.apache\&.commons\&.csv\&.CSVPrinter\&.printRecords (final Iterable<?> values) throws IOException"
Prints all the objects in the given collection handling nested collections/arrays as records\&.
.PP
If the given collection only contains simple objects, this method will print a single record like \fC\fBprintRecord(Iterable)\fP\fP\&. If the given collections contains nested collections/arrays those nested elements will each be printed as records using \fC\fBprintRecord(Object\&.\&.\&.)\fP\fP\&. 
.PP
Given the following data structure: 
.PP
.PP
.nf

\fC
List<String[]> data = \&.\&.\&.
data\&.add(new String[]{ 'A', 'B', 'C' });
data\&.add(new String[]{ '1', '2', '3' });
data\&.add(new String[]{ 'A1', 'B2', 'C3' });
\fP
.fi
.PP
.PP
Calling this method will print: 
.PP
.PP
.nf

\fC
A, B, C
1, 2, 3
A1, B2, C3
\fP
.fi
.PP
.PP
\fBParameters\fP
.RS 4
\fIvalues\fP the values to print\&. 
.RE
.PP
\fBExceptions\fP
.RS 4
\fIIOException\fP If an I/O error occurs 
.RE
.PP

.SS "void es\&.apachecsv\&.org\&.apache\&.commons\&.csv\&.CSVPrinter\&.printRecords (final Object\&.\&.\&. values) throws IOException"
Prints all the objects in the given array handling nested collections/arrays as records\&.
.PP
If the given array only contains simple objects, this method will print a single record like \fC\fBprintRecord(Object\&.\&.\&.)\fP\fP\&. If the given collections contains nested collections/arrays those nested elements will each be printed as records using \fC\fBprintRecord(Object\&.\&.\&.)\fP\fP\&. 
.PP
Given the following data structure: 
.PP
.PP
.nf

\fC
String[][] data = new String[3][]
data[0] = String[]{ 'A', 'B', 'C' };
data[1] = new String[]{ '1', '2', '3' };
data[2] = new String[]{ 'A1', 'B2', 'C3' };
\fP
.fi
.PP
.PP
Calling this method will print: 
.PP
.PP
.nf

\fC
A, B, C
1, 2, 3
A1, B2, C3
\fP
.fi
.PP
.PP
\fBParameters\fP
.RS 4
\fIvalues\fP the values to print\&. 
.RE
.PP
\fBExceptions\fP
.RS 4
\fIIOException\fP If an I/O error occurs 
.RE
.PP

.SS "void es\&.apachecsv\&.org\&.apache\&.commons\&.csv\&.CSVPrinter\&.printRecords (final ResultSet resultSet) throws SQLException, IOException"
Prints all the objects in the given JDBC result set\&.
.PP
\fBParameters\fP
.RS 4
\fIresultSet\fP result set the values to print\&. 
.RE
.PP
\fBExceptions\fP
.RS 4
\fIIOException\fP If an I/O error occurs 
.br
\fISQLException\fP if a database access error occurs 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for ProyectoFinalLDH from the source code\&.
