.TH "es.courserajava.edu.duke" 3 "Thu Dec 29 2022" "Version 1.0" "ProyectoFinalLDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
es.courserajava.edu.duke
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFileResource\fP"
.br
.ti -1c
.RI "class \fBFileSelector\fP"
.br
.ti -1c
.RI "class \fBImageFrame\fP"
.br
.ti -1c
.RI "class \fBImageResource\fP"
.br
.ti -1c
.RI "class \fBPixel\fP"
.br
.ti -1c
.RI "class \fBPoint\fP"
.br
.ti -1c
.RI "class \fBRangeResource\fP"
.br
.ti -1c
.RI "class \fBResourceException\fP"
.br
.ti -1c
.RI "class \fBShape\fP"
.br
.ti -1c
.RI "class \fBStorageResource\fP"
.br
.ti -1c
.RI "class \fBTextIterable\fP"
.br
.ti -1c
.RI "class \fBURLResource\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Resource classes for Duke/Coursera course\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for ProyectoFinalLDH from the source code\&.
