.TH "es.ull.etsii.Main" 3 "Sat Dec 3 2022" "Version 1.0" "ProyectoFinalLDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
es.ull.etsii.Main
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBmain\fP (String[] args)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
Stanislav Rakitov 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "static void es\&.ull\&.etsii\&.Main\&.main (String[] args)\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for ProyectoFinalLDH from the source code\&.
