.TH "es.ull.etsii.Movies.Movie" 3 "Wed Jan 4 2023" "Version 1.0" "ProyectoFinalLDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
es.ull.etsii.Movies.Movie
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMovie\fP (String anID, String aTitle, String aYear, String theGenres)"
.br
.ti -1c
.RI "\fBMovie\fP (String anID, String aTitle, String aYear, String theGenres, String aDirector, String aCountry, String aPoster, int theMinutes)"
.br
.ti -1c
.RI "String \fBgetID\fP ()"
.br
.ti -1c
.RI "String \fBgetTitle\fP ()"
.br
.ti -1c
.RI "int \fBgetYear\fP ()"
.br
.ti -1c
.RI "String \fBgetGenres\fP ()"
.br
.ti -1c
.RI "String \fBgetCountry\fP ()"
.br
.ti -1c
.RI "String \fBgetDirector\fP ()"
.br
.ti -1c
.RI "String \fBgetPoster\fP ()"
.br
.ti -1c
.RI "int \fBgetMinutes\fP ()"
.br
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "es\&.ull\&.etsii\&.Movies\&.Movie\&.Movie (String anID, String aTitle, String aYear, String theGenres)"

.SS "es\&.ull\&.etsii\&.Movies\&.Movie\&.Movie (String anID, String aTitle, String aYear, String theGenres, String aDirector, String aCountry, String aPoster, int theMinutes)"

.SH "Member Function Documentation"
.PP 
.SS "String es\&.ull\&.etsii\&.Movies\&.Movie\&.getCountry ()"

.SS "String es\&.ull\&.etsii\&.Movies\&.Movie\&.getDirector ()"

.SS "String es\&.ull\&.etsii\&.Movies\&.Movie\&.getGenres ()"

.SS "String es\&.ull\&.etsii\&.Movies\&.Movie\&.getID ()"

.SS "int es\&.ull\&.etsii\&.Movies\&.Movie\&.getMinutes ()"

.SS "String es\&.ull\&.etsii\&.Movies\&.Movie\&.getPoster ()"

.SS "String es\&.ull\&.etsii\&.Movies\&.Movie\&.getTitle ()"

.SS "int es\&.ull\&.etsii\&.Movies\&.Movie\&.getYear ()"

.SS "String es\&.ull\&.etsii\&.Movies\&.Movie\&.toString ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for ProyectoFinalLDH from the source code\&.
