.TH "es.ull.etsii.Rate" 3 "Sat Dec 3 2022" "Version 1.0" "ProyectoFinalLDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
es.ull.etsii.Rate
.SH SYNOPSIS
.br
.PP
.PP
Inherits Comparable< Rating >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRating\fP (String anItem, double aValue)"
.br
.ti -1c
.RI "String \fBgetItem\fP ()"
.br
.ti -1c
.RI "double \fBgetValue\fP ()"
.br
.ti -1c
.RI "String \fBtoString\fP ()"
.br
.ti -1c
.RI "int \fBcompareTo\fP (\fBRating\fP other)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "es\&.ull\&.etsii\&.Rating\&.Rating (String anItem, double aValue)"

.SH "Member Function Documentation"
.PP 
.SS "int es\&.ull\&.etsii\&.Rating\&.compareTo (\fBRating\fP other)"

.SS "String es\&.ull\&.etsii\&.Rating\&.getItem ()"

.SS "double es\&.ull\&.etsii\&.Rating\&.getValue ()"

.SS "String es\&.ull\&.etsii\&.Rating\&.toString ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for ProyectoFinalLDH from the source code\&.
