.TH "es.ull.etsii.Ratings.FirstRatings" 3 "Thu Dec 29 2022" "Version 1.0" "ProyectoFinalLDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
es.ull.etsii.Ratings.FirstRatings
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFirstRatings\fP (String fileName)"
.br
.ti -1c
.RI "\fBFirstRatings\fP (String fileNameMovies, String fileNameRaters)"
.br
.ti -1c
.RI "\fBFirstRatings\fP ()"
.br
.ti -1c
.RI "ArrayList< \fBMovie\fP > \fBloadMovies\fP (String filename)"
.br
.ti -1c
.RI "void \fBtestLoadMovies\fP ()"
.br
.ti -1c
.RI "void \fBtestLoadRaters\fP (String raterID, String movieID)"
.br
.in -1c
.SH "Detailed Description"
.PP 
A class to process the movie and ratings data and to answer questions about them\&.
.PP
\fBAuthor\fP
.RS 4
Stanislav Rakitov 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "es\&.ull\&.etsii\&.Ratings\&.FirstRatings\&.FirstRatings (String fileName)"

.SS "es\&.ull\&.etsii\&.Ratings\&.FirstRatings\&.FirstRatings (String fileNameMovies, String fileNameRaters)"

.SS "es\&.ull\&.etsii\&.Ratings\&.FirstRatings\&.FirstRatings ()"

.SH "Member Function Documentation"
.PP 
.SS "ArrayList< \fBMovie\fP > es\&.ull\&.etsii\&.Ratings\&.FirstRatings\&.loadMovies (String filename)"

.SS "void es\&.ull\&.etsii\&.Ratings\&.FirstRatings\&.testLoadMovies ()"
A void method for tests cases\&.
.PP
.PD 0
.IP "\(bu" 2
determine how many movies in total\&. 
.IP "\(bu" 2
determine how many movies include the Comedy genre\&. 
.IP "\(bu" 2
determine how many movies are greater than 150 minutes in length\&. 
.IP "\(bu" 2
determine the maximum number of movies by any director, and who the directors are that directed that many movies\&. 
.PP

.SS "void es\&.ull\&.etsii\&.Ratings\&.FirstRatings\&.testLoadRaters (String raterID, String movieID)"


.SH "Author"
.PP 
Generated automatically by Doxygen for ProyectoFinalLDH from the source code\&.
