.TH "es.ull.etsii.Filters.DirectorsFilter" 3 "Miércoles, 4 de Enero de 2023" "Version 1.0" "ProyectoFinalLDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
es.ull.etsii.Filters.DirectorsFilter
.SH SYNOPSIS
.br
.PP
.PP
Herencias \fBes\&.ull\&.etsii\&.Filters\&.Filter\fP\&.
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "\fBDirectorsFilter\fP (String directors)"
.br
.ti -1c
.RI "boolean \fBsatisfies\fP (String id)"
.br
.in -1c
.SH "Descripción detallada"
.PP 
A class for filter movies by directors
.PP
\fBAutor\fP
.RS 4
Stanislav Rakitov 
.RE
.PP
\fBVersión\fP
.RS 4
1\&.0 
.RE
.PP

.SH "Documentación del constructor y destructor"
.PP 
.SS "es\&.ull\&.etsii\&.Filters\&.DirectorsFilter\&.DirectorsFilter (String directors)"

.SH "Documentación de las funciones miembro"
.PP 
.SS "boolean es\&.ull\&.etsii\&.Filters\&.DirectorsFilter\&.satisfies (String id)"

.PP
Implementa \fBes\&.ull\&.etsii\&.Filters\&.Filter\fP\&.

.SH "Autor"
.PP 
Generado automáticamente por Doxygen para ProyectoFinalLDH del código fuente\&.
