.TH "es.ull.etsii.Rate.RaterDatabase" 3 "Sat Dec 3 2022" "Version 1.0" "ProyectoFinalLDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
es.ull.etsii.Rate.RaterDatabase
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBinitialize\fP (String filename)"
.br
.ti -1c
.RI "static void \fBaddRatings\fP (String filename)"
.br
.ti -1c
.RI "static void \fBaddRaterRating\fP (String raterID, String movieID, double rating)"
.br
.ti -1c
.RI "static \fBRater\fP \fBgetRater\fP (String id)"
.br
.ti -1c
.RI "static ArrayList< \fBRater\fP > \fBgetRaters\fP ()"
.br
.ti -1c
.RI "static int \fBsize\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static void es\&.ull\&.etsii\&.RaterDatabase\&.addRaterRating (String raterID, String movieID, double rating)\fC [static]\fP"

.SS "static void es\&.ull\&.etsii\&.RaterDatabase\&.addRatings (String filename)\fC [static]\fP"

.SS "static \fBRater\fP es\&.ull\&.etsii\&.RaterDatabase\&.getRater (String id)\fC [static]\fP"

.SS "static ArrayList< \fBRater\fP > es\&.ull\&.etsii\&.RaterDatabase\&.getRaters ()\fC [static]\fP"

.SS "static void es\&.ull\&.etsii\&.RaterDatabase\&.initialize (String filename)\fC [static]\fP"

.SS "static int es\&.ull\&.etsii\&.RaterDatabase\&.size ()\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for ProyectoFinalLDH from the source code\&.
