.TH "es.ull.etsii.Ratings.MovieRunnerSimilarRatings" 3 "Miércoles, 4 de Enero de 2023" "Version 1.0" "ProyectoFinalLDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
es.ull.etsii.Ratings.MovieRunnerSimilarRatings
.SH SYNOPSIS
.br
.PP
.SS "Métodos públicos"

.in +1c
.ti -1c
.RI "void \fBprintAverageRatings\fP (int minimalRatings)"
.br
.ti -1c
.RI "void \fBprintAverageRatingsByYearAfterAndGenre\fP (int minimalRatings, int year, String genre)"
.br
.ti -1c
.RI "void \fBprintSimilarRatings\fP ()"
.br
.ti -1c
.RI "void \fBprintSimilarRatingsByGenre\fP ()"
.br
.ti -1c
.RI "void \fBprintSimilarRatingsByDirector\fP ()"
.br
.ti -1c
.RI "void \fBprintSimilarRatingsByGenreAndMinutes\fP ()"
.br
.ti -1c
.RI "void \fBprintSimilarRatingsByYearAfterAndMinutes\fP ()"
.br
.in -1c
.SH "Descripción detallada"
.PP 

.PP
\fBAutor\fP
.RS 4
Stanislav Rakitov 
.RE
.PP

.SH "Documentación de las funciones miembro"
.PP 
.SS "void es\&.ull\&.etsii\&.Ratings\&.MovieRunnerSimilarRatings\&.printAverageRatings (int minimalRatings)"
Print a list of movies and their average ratings sorted by averages
.PP
\fBParámetros\fP
.RS 4
\fIminimalRatings\fP int specified number of ratings 
.RE
.PP

.SS "void es\&.ull\&.etsii\&.Ratings\&.MovieRunnerSimilarRatings\&.printAverageRatingsByYearAfterAndGenre (int minimalRatings, int year, String genre)"

.SS "void es\&.ull\&.etsii\&.Ratings\&.MovieRunnerSimilarRatings\&.printSimilarRatings ()"

.SS "void es\&.ull\&.etsii\&.Ratings\&.MovieRunnerSimilarRatings\&.printSimilarRatingsByDirector ()"

.SS "void es\&.ull\&.etsii\&.Ratings\&.MovieRunnerSimilarRatings\&.printSimilarRatingsByGenre ()"

.SS "void es\&.ull\&.etsii\&.Ratings\&.MovieRunnerSimilarRatings\&.printSimilarRatingsByGenreAndMinutes ()"

.SS "void es\&.ull\&.etsii\&.Ratings\&.MovieRunnerSimilarRatings\&.printSimilarRatingsByYearAfterAndMinutes ()"


.SH "Autor"
.PP 
Generado automáticamente por Doxygen para ProyectoFinalLDH del código fuente\&.
