.TH "es.ull.etsii.Movies.MovieDatabase" 3 "Thu Dec 29 2022" "Version 1.0" "ProyectoFinalLDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
es.ull.etsii.Movies.MovieDatabase
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBinitialize\fP (String moviefile)"
.br
.ti -1c
.RI "static boolean \fBcontainsID\fP (String id)"
.br
.ti -1c
.RI "static int \fBgetYear\fP (String id)"
.br
.ti -1c
.RI "static String \fBgetGenres\fP (String id)"
.br
.ti -1c
.RI "static String \fBgetTitle\fP (String id)"
.br
.ti -1c
.RI "static \fBMovie\fP \fBgetMovie\fP (String id)"
.br
.ti -1c
.RI "static String \fBgetPoster\fP (String id)"
.br
.ti -1c
.RI "static int \fBgetMinutes\fP (String id)"
.br
.ti -1c
.RI "static String \fBgetCountry\fP (String id)"
.br
.ti -1c
.RI "static String \fBgetDirector\fP (String id)"
.br
.ti -1c
.RI "static int \fBsize\fP ()"
.br
.ti -1c
.RI "static ArrayList< String > \fBfilterBy\fP (\fBFilter\fP f)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static boolean es\&.ull\&.etsii\&.Movies\&.MovieDatabase\&.containsID (String id)\fC [static]\fP"

.SS "static ArrayList< String > es\&.ull\&.etsii\&.Movies\&.MovieDatabase\&.filterBy (\fBFilter\fP f)\fC [static]\fP"

.SS "static String es\&.ull\&.etsii\&.Movies\&.MovieDatabase\&.getCountry (String id)\fC [static]\fP"

.SS "static String es\&.ull\&.etsii\&.Movies\&.MovieDatabase\&.getDirector (String id)\fC [static]\fP"

.SS "static String es\&.ull\&.etsii\&.Movies\&.MovieDatabase\&.getGenres (String id)\fC [static]\fP"

.SS "static int es\&.ull\&.etsii\&.Movies\&.MovieDatabase\&.getMinutes (String id)\fC [static]\fP"

.SS "static \fBMovie\fP es\&.ull\&.etsii\&.Movies\&.MovieDatabase\&.getMovie (String id)\fC [static]\fP"

.SS "static String es\&.ull\&.etsii\&.Movies\&.MovieDatabase\&.getPoster (String id)\fC [static]\fP"

.SS "static String es\&.ull\&.etsii\&.Movies\&.MovieDatabase\&.getTitle (String id)\fC [static]\fP"

.SS "static int es\&.ull\&.etsii\&.Movies\&.MovieDatabase\&.getYear (String id)\fC [static]\fP"

.SS "static void es\&.ull\&.etsii\&.Movies\&.MovieDatabase\&.initialize (String moviefile)\fC [static]\fP"

.SS "static int es\&.ull\&.etsii\&.Movies\&.MovieDatabase\&.size ()\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for ProyectoFinalLDH from the source code\&.
