.TH "es.ull.etsii.Recommendations.RecommendationRunner" 3 "Wed Jan 4 2023" "Version 1.0" "ProyectoFinalLDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
es.ull.etsii.Recommendations.RecommendationRunner
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBes\&.ull\&.etsii\&.Recommendations\&.Recommender\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "ArrayList< String > \fBgetItemsToRate\fP ()"
.br
.ti -1c
.RI "void \fBprintRecommendationsFor\fP (String webRaterID)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor\fP
.RS 4
Stanislav Rakitov 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "ArrayList< String > es\&.ull\&.etsii\&.Recommendations\&.RecommendationRunner\&.getItemsToRate ()"
This method returns a list of movie IDs that will be used to look up the movies in the MovieDatabase and present them to users to rate\&.
.PP
The movies returned in the list will be displayed on a web page, so the number you choose may affect how long the page takes to load and how willing users are to rate the movies\&. For example, 10-20 should be fine, 50 or more would be too many\&.
.PP
There are no restrictions on the method you use to generate this list of movies: the most recent movies, movies from a specific genre, randomly chosen movies, or simply your favorite movies\&.
.PP
The ratings for these movies will make the profile for a new Rater that will be used to compare to for finding recommendations\&. 
.PP
Implements \fBes\&.ull\&.etsii\&.Recommendations\&.Recommender\fP\&.
.SS "void es\&.ull\&.etsii\&.Recommendations\&.RecommendationRunner\&.printRecommendationsFor (String webRaterID)"
This method returns nothing, but prints out an HTML table of the movies recommended for the given rater\&.
.PP
The HTML printed will be displayed on a web page, so the number you choose to display may affect how long the page takes to load\&. For example, you may want to limit the number printed to only the top 20-50 movies recommended or to movies not rater by the given rater\&.
.PP
You may also include CSS styling for your table using the <style> tag before you print the table\&. There are no restrictions on which movies you print, what order you print them in, or what information you include about each movie\&.
.PP
\fBParameters\fP
.RS 4
\fIwebRaterID\fP the ID of a new Rater that has been already added to the RaterDatabase with ratings for the movies returned by the method getItemsToRate 
.RE
.PP

.PP
Implements \fBes\&.ull\&.etsii\&.Recommendations\&.Recommender\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ProyectoFinalLDH from the source code\&.
