.TH "C:/Users/roberto/IdeaProjects/LDH_PFInal/src/main/java/es/ull/etsii/Ratings/FourthRatings.java" 3 "Wed Jan 4 2023" "Version 1.0" "ProyectoFinalLDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/roberto/IdeaProjects/LDH_PFInal/src/main/java/es/ull/etsii/Ratings/FourthRatings.java
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBes\&.ull\&.etsii\&.Ratings\&.FourthRatings\fP"
.br
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBes\&.ull\&.etsii\&.Ratings\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ProyectoFinalLDH from the source code\&.
