.TH "ull" 3 "Thu Dec 1 2022" "Version 1.0" "ProyectoFinalLDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ull
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAllFilters\fP"
.br
.ti -1c
.RI "class \fBDirectorsFilter\fP"
.br
.ti -1c
.RI "class \fBEfficientRater\fP"
.br
.ti -1c
.RI "interface \fBFilter\fP"
.br
.ti -1c
.RI "class \fBFirstRatings\fP"
.br
.ti -1c
.RI "class \fBFourthRatings\fP"
.br
.ti -1c
.RI "class \fBGenreFilter\fP"
.br
.ti -1c
.RI "class \fBMinutesFilter\fP"
.br
.ti -1c
.RI "class \fBMovie\fP"
.br
.ti -1c
.RI "class \fBMovieDatabase\fP"
.br
.ti -1c
.RI "class \fBMovieRunnerSimilarRatings\fP"
.br
.ti -1c
.RI "interface \fBRater\fP"
.br
.ti -1c
.RI "class \fBRaterDatabase\fP"
.br
.ti -1c
.RI "class \fBRating\fP"
.br
.ti -1c
.RI "class \fBRecommendationRunner\fP"
.br
.ti -1c
.RI "interface \fBRecommender\fP"
.br
.ti -1c
.RI "class \fBTrueFilter\fP"
.br
.ti -1c
.RI "class \fBYearAfterFilter\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for ProyectoFinalLDH from the source code\&.
