.TH "ull.DirectorsFilter" 3 "Thu Dec 1 2022" "Version 1.0" "ProyectoFinalLDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ull.DirectorsFilter
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBull\&.Filter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDirectorsFilter\fP (String directors)"
.br
.ti -1c
.RI "boolean \fBsatisfies\fP (String id)"
.br
.in -1c
.SH "Detailed Description"
.PP 
A class for filter movies by directors
.PP
\fBAuthor\fP
.RS 4
Stanislav Rakitov 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "ull\&.DirectorsFilter\&.DirectorsFilter (String directors)"

.SH "Member Function Documentation"
.PP 
.SS "boolean ull\&.DirectorsFilter\&.satisfies (String id)"

.PP
Implements \fBull\&.Filter\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ProyectoFinalLDH from the source code\&.
