.TH "ull.FourthRatings" 3 "Thu Dec 1 2022" "Version 1.0" "ProyectoFinalLDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ull.FourthRatings
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "ArrayList< \fBRating\fP > \fBgetAverageRatings\fP (int minimalRaters)"
.br
.ti -1c
.RI "ArrayList< \fBRating\fP > \fBgetAverageRatingsByFilter\fP (Integer minimalRaters, \fBFilter\fP filterCriteria)"
.br
.ti -1c
.RI "double \fBdotProduct\fP (\fBRater\fP meRater, \fBRater\fP otherRater)"
.br
.ti -1c
.RI "ArrayList< \fBRating\fP > \fBgetSimilarRatings\fP (String id, Integer numSimilarRaters, Integer minimalRaters)"
.br
.ti -1c
.RI "ArrayList< \fBRating\fP > \fBgetSimilarRatingsByFilter\fP (String id, Integer numSimilarRaters, Integer minimalRaters, \fBFilter\fP filterCriteria)"
.br
.in -1c
.SH "Detailed Description"
.PP 
The week 4 class
.PP
\fBAuthor\fP
.RS 4
Stanislav Rakitov 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "double ull\&.FourthRatings\&.dotProduct (\fBRater\fP meRater, \fBRater\fP otherRater)"

.SS "ArrayList< \fBRating\fP > ull\&.FourthRatings\&.getAverageRatings (int minimalRaters)"

.SS "ArrayList< \fBRating\fP > ull\&.FourthRatings\&.getAverageRatingsByFilter (Integer minimalRaters, \fBFilter\fP filterCriteria)"

.SS "ArrayList< \fBRating\fP > ull\&.FourthRatings\&.getSimilarRatings (String id, Integer numSimilarRaters, Integer minimalRaters)"

.SS "ArrayList< \fBRating\fP > ull\&.FourthRatings\&.getSimilarRatingsByFilter (String id, Integer numSimilarRaters, Integer minimalRaters, \fBFilter\fP filterCriteria)"


.SH "Author"
.PP 
Generated automatically by Doxygen for ProyectoFinalLDH from the source code\&.
