.TH "ull.GenreFilter" 3 "Thu Dec 1 2022" "Version 1.0" "ProyectoFinalLDH" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ull.GenreFilter
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBull\&.Filter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGenreFilter\fP (String genre)"
.br
.ti -1c
.RI "boolean \fBsatisfies\fP (String id)"
.br
.in -1c
.SH "Detailed Description"
.PP 
A class for filter movies by genre
.PP
\fBAuthor\fP
.RS 4
Stanislav Rakitov 
.RE
.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "ull\&.GenreFilter\&.GenreFilter (String genre)"

.SH "Member Function Documentation"
.PP 
.SS "boolean ull\&.GenreFilter\&.satisfies (String id)"

.PP
Implements \fBull\&.Filter\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for ProyectoFinalLDH from the source code\&.
